---

- name: Configure RabbitMQ
  ansible.builtin.template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    owner: root
    group: rabbitmq
    mode: "0640"
  notify: Restart RabbitMQ

- name: Set Erlang cookie
  ansible.builtin.copy:
    content: "{{ rabbitmq_erlang_cookie }}"
    dest: "{{ rabbitmq_erlang_cookie_file }}"
    owner: root
    group: rabbitmq
    mode: "0640"
  when: rabbitmq_cluster
  notify: Restart RabbitMQ
