---

- name: Disable RabbitMQ plugins
  community.rabbitmq.rabbitmq_plugin:
    names: "{{ item.names }}"
    state: disabled
  loop: "{{ rabbitmq_plugins | default([]) }}"
  when: item.state is defined and item.state == "disabled"

- name: Enable RabbitMQ plugins
  community.rabbitmq.rabbitmq_plugin:
    names: "{{ item.names }}"
    broker_state: "{{ item.broker_state | default(omit) }}"
    prefix: "{{ item.prefix | default(omit) }}"
    new_only: "{{ item.new_only | default(omit) }}"
    state: enabled
  loop: "{{ rabbitmq_plugins | default([]) }}"
  when: item.state is not defined or item.state == "enabled"
