---

- name: Remove RabbitMQ vhosts
  community.rabbitmq.rabbitmq_vhost:
    node: "{{ rabbitmq_node }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ rabbitmq_vhosts | default([]) }}"
  when: item.state is defined and item.state == "absent"

- name: Create RabbitMQ vhosts
  community.rabbitmq.rabbitmq_vhost:
    node: "{{ rabbitmq_node }}"
    name: "{{ item.name }}"
    tracing: "{{ item.tracing | default(omit) }}"
    state: present
  loop: "{{ rabbitmq_vhosts | default([]) }}"
  when: item.state is not defined or item.state == "present"
